path_gams = '../../../GAMS/'
path_pycore = '../../../pycore/'
path_enz_mw = '../../../input/enz_mw_g_per_mmol.txt'
path_pro_mw = '../../../input/pro_mw_g_per_mmol.txt'
biom_id = 'BIOSYN-BIODILAERO-NOGAM'
biom_id_fba = 'BIOMASS'
vprod_coreid = 'EX_13ppd_e'
vprod = 'RXNADD-EX_13ppd_e_FWD-SPONT'
c_sources_list = [{'rxn': 'EX_glc__D_e', 'MW': 180.156, 'v': -4.288673059831686}]
prod_mw = 76.09
